"""Reusable AcademyInfo API helpers."""

from .client import (
    AcademyInfoClient,
    ProbeDefaults,
    load_service_key,
    load_yaml,
    representative_params,
)
from .collection import (
    AcademyInfoCollector,
    CollectionError,
    CollectionPolicy,
    CollectionRun,
    FailedTask,
    SchoolDiscovery,
    TaskExecutionError,
    TaskResult,
    VerifiedRowLimitError,
    school_ids_from_xml,
    select_endpoint_config,
)
from .downloader import (
    AcademyInfoDownloadError,
    AcademyInfoDownloader,
    AcademyInfoLocalIOError,
    TemporaryXmlDownload,
    XmlResponseMetadata,
    parse_xml_metadata,
)
from .planning import (
    CollectionPlanningError,
    CollectionTask,
    build_collection_tasks,
)
from .storage import (
    AcademyInfoStorage,
    CollectionMetadata,
    DownloadIntegrityError,
    ManifestIntegrityError,
    ManifestRecord,
    RawPathConflictError,
    SaveResult,
    StorageError,
    TaskConflictError,
    UnsafeParameterError,
    safe_params,
)
from .validation import (
    ValidationContext,
    ValidationError,
    ValidationRun,
    load_validation_context,
    run_validation,
)

__all__ = [
    "AcademyInfoClient",
    "ProbeDefaults",
    "load_service_key",
    "load_yaml",
    "representative_params",
    "AcademyInfoCollector",
    "CollectionError",
    "CollectionPolicy",
    "CollectionRun",
    "FailedTask",
    "SchoolDiscovery",
    "TaskExecutionError",
    "TaskResult",
    "VerifiedRowLimitError",
    "school_ids_from_xml",
    "select_endpoint_config",
    "AcademyInfoDownloadError",
    "AcademyInfoDownloader",
    "AcademyInfoLocalIOError",
    "TemporaryXmlDownload",
    "XmlResponseMetadata",
    "parse_xml_metadata",
    "CollectionPlanningError",
    "CollectionTask",
    "build_collection_tasks",
    "AcademyInfoStorage",
    "CollectionMetadata",
    "DownloadIntegrityError",
    "ManifestIntegrityError",
    "ManifestRecord",
    "RawPathConflictError",
    "SaveResult",
    "StorageError",
    "TaskConflictError",
    "UnsafeParameterError",
    "safe_params",
    "ValidationContext",
    "ValidationError",
    "ValidationRun",
    "load_validation_context",
    "run_validation",
]
